# Generated by Django 4.1.3 on 2022-11-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(max_length=60)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
